name: Release

on:
  push:
    tags:
      - v*.*

jobs:
  CI:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish Docker
        env:
          DOCKER_PUSH: true
          DOCKER_REPOSITORY: ghcr.io/jarvis-u/config-server-ui
          DOCKER_TAG: ${{ github.ref_name }}
        run: |
          # Build Docker image
          docker build -t $DOCKER_REPOSITORY:$DOCKER_TAG -f Dockerfile .
          # Push Docker image
          docker push $DOCKER_REPOSITORY:$DOCKER_TAG

  result:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: [CI]
    steps:
      - name: Build Result
        run: echo "Just to make the GitHub merge button green"
